### PR TITLE
nitpick of reddits sup text crappiness

### PR DESCRIPTION
**Pull request by NeatNit**
I didn't actually test this because I don't know how, and also I don't know python so I'm not sure if this can be broken up into multiple lines without inserting a newline character between them, but, this syntax - replacing spaces with `&#32;`, forces reddit to treat the whole thing as if it's just one word, meaning there's no shittiness with the way it's rendered on different devices.

### CODE REVIEW

**Comment by NeatNit** [comment]
also fixed a mistake in the feedback link - you don't need /u/ in PMs.

**Comment by aquelemiguel** [comment]
Thank you for the corrections! On which device did you have issues with `&#32`?

**Comment by NeatNit** [comment]
Admittedly I've never experienced an issue myself (just bothers me as a general computer nerd knowing that there's a better way), but here's a screenshot someone sent me when I offered a similar fix for a different bot:

screenshot

Context: https://www.reddit.com/r/TranscribersOfReddit/comments/6ee9p4/meta_better_signature_markup/

In that same thread, you may notice another issue being fixed - the underlines between words in links. Most subs don't have underlines for links, but those that do... ew.

**Comment by it-is-wednesday** [comment]
You can break it into multiple lines if you put a `\` at the end of each line but the last one

**Comment by aquelemiguel** [comment]
Perfect, thank you for the corrections. Will commit later!

**Comment by NeatNit** [comment]
The change in 03e6c4c70cc482c2455483f419590c0930fbb22f doesn't really do anything. It's still this:
image
While mine is:
image

You have to actually have `"&#32;"` in your string, the `\x20` method just makes a regular space character anyway.

**Comment by aquelemiguel** [comment]
@NeatNit I've tried fixing this (you may check my latest commit) to no avail.  
Adding `&#32;` to interferes with Python's comment syntax. I'm afraid converting the `&#32;` entity to a HTML character didn't really do much - check `html.unescape('&#32;')`.  
Could you please check if the bot's latest comments are fixed? On my phone they still look odd.

**Comment by NeatNit** [comment]
You shouldn't be unescaping anything. The actual string that you send to the server needs to contain no spaces within the relevant text, and the actual characters `&#32;`. I don't know how Python plays with that, though. I'd *expect* that if you're within a string (incl. multiline) you can use `#`  without starting a comment, and I don't see why `&` or `;` would have a special meaning.

All of the recent comments look the same as always on my end (looking at the HTML result), although the feedback PM link is fixed.

**Comment by aquelemiguel** [comment]
Unfortunately,  `print("&#32;")` returns `&#32:` instead of the whitespace.  
It's pretty redundant, because unescaping `&#32;` obviously leaves us with just a regular whitespace. This would only work if Python actually recognized HTML numbers. Still haven't found a solution for it.

**Comment by NeatNit** [comment]
I think if you just do `s = '&#32;'` instead of  using `html.unescape`, it will work - but you need to change/remove the `^` characters as well.

**Comment by NeatNit** [comment]
>Unfortunately, print("&#32") returns &#32 instead of the whitespace.

Exactly what you want. (I assume you mean with the ; at the end)

We're trying to trick Reddit, not Python.

**Comment by aquelemiguel** [comment]
Oh shit. You're telling me that Reddit recognizes the string `&#32;` and fixes the spacing?

**Comment by NeatNit** [comment]
Yup.

https://www.reddit.com/r/test/comments/5re2hf/testing_long_sup_text/

Here's the post's 'source code' when I click Edit:
```
^^^(supposed to work but broken)

^^^fixed,&#32;hopefully.&#32;I&#32;also&#32;need&#32;to&#32;know&#32;if&#32;this&#32;works&#32;with&#32;really&#32;long&#32;sequences&#32;that&#32;need&#32;line&#32;breaks,&#32;so&#32;enjoy&#32;the&#32;following&#32;word&#32;repeated:&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization

okay it works, but here's some pre-text! ^^^fixed,&#32;hopefully.&#32;I&#32;also&#32;need&#32;to&#32;know&#32;if&#32;this&#32;works&#32;with&#32;really&#32;long&#32;sequences&#32;that&#32;need&#32;line&#32;breaks,&#32;so&#32;enjoy&#32;the&#32;following&#32;word&#32;repeated:&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization

^^^fixed,&#32;hopefully.&#32;I&#32;also&#32;need&#32;to&#32;know&#32;if&#32;this&#32;works&#32;with&#32;really&#32;long&#32;sequences&#32;that&#32;need&#32;line&#32;breaks,&#32;so&#32;enjoy&#32;the&#32;following&#32;word&#32;repeated:&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization and here's some post-text!

and here's ^^^fixed,&#32;hopefully.&#32;I&#32;also&#32;need&#32;to&#32;know&#32;if&#32;this&#32;works&#32;with&#32;really&#32;long&#32;sequences&#32;that&#32;need&#32;line&#32;breaks,&#32;so&#32;enjoy&#32;the&#32;following&#32;word&#32;repeated:&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization&#32;uncharacterization both!
```

**Comment by aquelemiguel** [comment]
Damn, feeling retarded. Thank you for your work!

**Pull request closed without merging**
